[2023-07-02 23:21:10,463] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-02 23:21:10,513] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-02 23:21:10,513] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-02 23:21:10,521] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-02 23:21:10,521] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-02 23:21:10,607] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_data> on 2023-07-01 00:00:00+00:00
[2023-07-02 23:21:10,613] {standard_task_runner.py:52} INFO - Started process 19538 to run task
[2023-07-02 23:21:10,618] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_weather', 'extract_data', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/dag_weather.py', '--cfg-path', '/tmp/tmpwg0nymex', '--error-file', '/tmp/tmpwmx1k7ra']
[2023-07-02 23:21:10,619] {standard_task_runner.py:80} INFO - Job 130: Subtask extract_data
[2023-07-02 23:21:11,046] {task_command.py:371} INFO - Running <TaskInstance: dag_weather.extract_data scheduled__2023-07-01T00:00:00+00:00 [running]> on host db753b024971
[2023-07-02 23:21:11,305] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=MariaRO
AIRFLOW_CTX_DAG_ID=dag_weather
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-01T00:00:00+00:00
[2023-07-02 23:21:11,309] {logging_mixin.py:115} INFO - ***************
[2023-07-02 23:21:11,309] {logging_mixin.py:115} INFO - 2023-07-01
[2023-07-02 23:21:12,804] {logging_mixin.py:115} INFO - Expecting value: line 1 column 1 (char 0)
[2023-07-02 23:21:12,824] {logging_mixin.py:115} INFO - Expecting value: line 1 column 1 (char 0)
[2023-07-02 23:21:12,847] {logging_mixin.py:115} INFO - Expecting value: line 1 column 1 (char 0)
[2023-07-02 23:21:12,871] {logging_mixin.py:115} INFO - Expecting value: line 1 column 1 (char 0)
[2023-07-02 23:21:12,898] {logging_mixin.py:115} INFO - Expecting value: line 1 column 1 (char 0)
[2023-07-02 23:21:12,899] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_weather.py", line 49, in extract_data
    df = pd.concat(df_list)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 304, in concat
    sort=sort,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 374, in __init__
    raise ValueError("All objects passed were None")
ValueError: All objects passed were None
[2023-07-02 23:21:12,911] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather, task_id=extract_data, execution_date=20230701T000000, start_date=20230702T232110, end_date=20230702T232112
[2023-07-02 23:21:12,939] {standard_task_runner.py:97} ERROR - Failed to execute job 130 for task extract_data (All objects passed were None; 19538)
[2023-07-02 23:21:12,964] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-02 23:21:13,024] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
